### ISSUE TITLE
Everyone could link to the ticket

### ISSUE THREAD

**Issue by chan15** [maxrossello/redmine_extended_watchers#17]
I already set the the permission that user can only see the ticket he opened or assigned to him, but after installed this plugin, the permission is not only open for the watcher, everyone could access the ticket by the link

**Comment by maxrossello** [comment]
Thank you for reporting this, I acknowledge the problem.

In the meanwhile, if you are using the master branch, remove the "view own" permission since it is not necessary for the scope (you may use the "with view own" branch if you want to have the permission mandatorily set for the issue to be visible). 
On master, with no permissions set, the user will see the issue if and only if he is set as a watcher.

**Comment by chan15** [comment]
I am not familiar with Rails, will you fix this? appreciated

**Comment by maxrossello** [comment]
I will, although I need to cope with other priority tasks

**Comment by chan15** [comment]
Thanks a lot

**Comment by akurutin** [comment]
> I already set the the permission that user can only see the ticket he opened or assigned to him

sorry for the offtop, but how did you do that?

**Comment by akurutin** [comment]
Does the branch solve the problem or not? Can I assign users not from the project as watchers?

**Comment by maxrossello** [comment]
The plugin has been refreshed and now supports Redmine 3.4.13.
I believe your problem should be solved. Please reopen the ticket if not.
Thanks
