### ISSUE TITLE
redmine 5.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [maxrossello/redmine_extended_watchers#50]
Is it possible to update to the latest version of redmine 5.1 ?
is there a need for this plugin with the updates that have become available in redmine 5.1 auto watch?

**Comment by maxrossello** [comment]
I do this in my spare time so it needs time to make all plugins that I support to work properly together at production grade.

However, I can say from my internal tests that this plugin is not requiring any relevant change wrt the version that targets Redmine 5.0.2 onward. So, for the moment you can install that over Redmine 5.1; then a specific version branching will come anytime soon with "official" support.

The auto watch feature does not clash with this plugin, since it is basically just a new way to set the watching flag, then all the rest that involves permissions works as usual
