### ISSUE TITLE
Add notes to project

### ISSUE THREAD

**Issue by aseques** [maxrossello/redmine_extended_watchers#52]
Hi, I've been using this plugin for about a year and it works great, today one of the users requested if it was possible to add notes to an issue that's been shared via extended watchers.
By reading the plugin description it seems that's not possible (at least for now). Could you confirm it (and if you know some directions to accomplish this would be great too)

Thanks a lot for your work

**Comment by maxrossello** [comment]
Hi,
I suppose you're using the Extended mode. That is a quick and easy way to extend the issue visibility to anyone that's not engaged into a project, but in this mode there's no way to manage the single permission.

If you need more control, then you have to use the Protected mode. You may set the desired settings on the nonmember role (considered when a user has no role in the project, i.e. is not a member), or create a new role to define the set of users that can be engaged via watch and set your desired permissions there, or both. 

These roles should grant visibility for owned and assigned issues, being watching an issue a third additional visibility criteria. Once an issue can be viewed (because of watching or for any of the other two criteria), all related permissions apply in full granularity.

In this mode, the possibility to assign a watch is restricted to the meaningfulness of these terms. So non-members cannot be watched unless the nonmember role is properly configured.

Hope this helps.

**Comment by aseques** [comment]
Hi @maxrossello  I'm finally testing this, there's something I'm missing though, on your comment you say:

> being watching an issue a third additional visibility criteria
I checked for this option on the role creation and in the project settings and I can't find anything related, where should this option be? 

Thanks a lot

**Comment by maxrossello** [comment]
Hi,
I mean that when you select issue visibility in a role as "Issues created by or assigned to the user", then this is enhanced to include watched issues too

**Comment by aseques** [comment]
Thanks @maxrossello, it finally made sense (it's more complicated than with the extended as you said), i created a new role (not using nonmembers) called viewers that has:

- Visiblity: "Issues created by or assigned to the user"
- View Issues + Add Notes + Edit Issues (to change the status)
- Assigned the trackers to the permissions (in the "Issue tracking" part)

Then I added this role with the user group to the top level projects (inherited to the subprojects)

Now the users in the selected groups can granularly do what I wanted on the watched issues


Thanks a lot

**Comment by maxrossello** [comment]
Thanks for reporting your use case and success!

**Comment by aseques** [comment]
Thanks @maxrossello, it finally made sense (it's more complicated than with the extended as you said), i created a new role (not using nonmembers) called viewers that has:

- Visiblity: "Issues created by or assigned to the user"
- View Issues + Add Notes + Edit Issues (to change the status)
- Assigned the trackers to the permissions (in the "Issue tracking" part)

Then I added this role with the user group to the top level projects (inherited to the subprojects)

Now the users in the selected groups can granularly do what I wanted on the watched issues


Thanks a lot
